---
- hosts: localhost
  tasks:
  - name: Install Ubuntu apps (apparantly there is a snap module coming in Ansible 2.8)
    command: snap install {{ item }} 
    become: yes
    with_items:
      - slack --classic
      - spotify
      - rocketchat-desktop
      - chromium
      - firefox
      - atom --classic
      - tmux --classic
      - evernote-web-client
      - docker
    when: ansible_distribution == 'Ubuntu'

  - name: Install osx apps with brew cask
    homebrew_cask: name={{ item }}
    with_items:
      - slack 
      - spotify
      - rocket-chat
      - google-chrome 
      - firefox
      - atom 
      - evernote 
      - docker
    when: ansible_distribution == 'MacOSX'
    ignore_errors: yes

  - name: Install osx apps with brew 
    homebrew: name={{ item }}
    with_items:
      - tmux
    when: ansible_distribution == 'MacOSX'

 
